<a href="https://colab.research.google.com/github/FereshtehRD/DataScience2/blob/FereshtehRD-homework1/Homework2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import datasets
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import naive_bayes
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import roc_curve, auc
from itertools import cycle
from scipy import interp
from sklearn.datasets import load_boston
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier


In [ ]:
#read dataset by using datasets function from sklearn
digits = datasets.load_digits()
#using zip function to integreate both data and target
#data_and_labels=list(zip(digits.data, digits.target))
#what does this function do? what is the point here?
#np.random.seed(123)
#divide the data to test and train
x_train, x_test, y_train, y_test= train_test_split(digits.data, digits.target, test_size=0.3, shuffle=True)


In [ ]:
#by using numpy liberary we can find the index of images that are 9 and others
index_9=np.where(y_train==9)
index_n9=np.where(y_train!=9)


In [ ]:
#digits=load_digits()
#x_train, x_test, y_train, y_test= train_test_split(digits.data, digits.target, test_size=0.3, random_state=33)
#ss=StandardScaler()
#X_train=ss.fit_transform(x_train)
#X_test=ss.transform(x_test)
#index_9=np.where(y_train==9)
#index_n9=np.where(y_train!=9)
#seperrate 9 and n9 images
x_train_9=x_train[index_9]
x_train_n9=x_train[index_n9]
#calculate the number of 9 images in the dataset
num_9=len(index_9[0])
print(num_9)
#put the indexes in order using numpy assary
array_n9=np.asarray(index_n9)
#from data set array_n9 we want to choose randomly num_9 sample (the same number of sample that we have as 9 images)
index_n9_rd=np.random.choice(array_n9.shape[1],size=num_9, replace=False, p=None)
#import indexes to have the data
x_train_n9_rd=x_train_n9[index_n9_rd]
#in this moment we have 123 images which the number is 9 and 123 images which the number is not 9

123


In [ ]:
#here we do a binay classification puting -1 when there output is 9 and otherwise
y_test[y_test!=9]=-1
y_test[y_test==9]=1
#create a concrete dataset
x_train=np.concatenate((x_train_9, x_train_n9_rd), axis=0)
#put y_train for the 123 rows 1 since they are the images with output 9 and otherwise.
y_train=np.ones(2*num_9)
y_train[num_9:]=-1


In [ ]:
from sklearn.linear_model import LogisticRegression
#fit the model
logistic=LogisticRegression(random_state=0, penalty='none')
logit_reg=logistic.fit(x_train,y_train)
#predict on account of x_test
logit_pred=logit_reg.predict(x_test)
#see the percentage of correct responses.
sum(y_test==logit_pred)/(y_test.shape)

array([0.95740741])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=2)
knn.fit(x_train,y_train)
knn_pred= knn.predict(x_test)
sum(y_test==knn_pred)/(y_test.shape)

array([0.98518519])

In [ ]:
from sklearn import svm, datasets
svm=svm.SVC(kernel='linear', C=1, decision_function_shape='ovo').fit(x_train,y_train)
svm_pred=svm.predict(x_test)
sum(y_test==svm_pred)/(y_test.shape)


array([0.93333333])

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb_pred=gnb.fit(x_train, y_train).predict(x_test)
sum(y_test==gnb_pred)/(y_test.shape)

array([0.79259259])

In [ ]:
#calculate confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, logit_pred)
confusion_matrix(y_test, knn_pred)
confusion_matrix(y_test, svm_pred)
confusion_matrix(y_test, gnb_pred)

array([[380, 105],
       [  7,  48]])

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, logit_pred)
f1_score(y_test, knn_pred)
f1_score(y_test, svm_pred)
f1_score(y_test, gnb_pred)
####what is f1_score

0.4615384615384615

1-4
One way to use the previous models to classify all 10 classes in the dataset would be to use the one-vs-all method. Using this method, we would test each individual class vs the rest of the classes similar to the above method (i.e. classify all sevenss vs non-sevens) and repeat for each individual class. We would then classify a given point by choosing the model that is the most confident in its classification.

In [ ]:
#import boston dataset
boston=datasets.load_boston()
#have a table
bostondata_pd=pd.DataFrame(boston.data)
#name of the columns of the dataset be the features of the boston
bostondata_pd.columns=boston.feature_names
#create a column of dataset
bostontarget_pd=pd.DataFrame(boston.target)
rm=np.asarray(bostondata_pd.RM)
age=np.asarray(bostondata_pd.AGE)
#name the target as medv
bostontarget_pd.columns=["MEDV"]
medv=np.asarray(bostontarget_pd.MEDV)
rm=rm.reshape(-1,1)
age=age.reshape(-1,1)
#having simple linear regression
linear_rg=LinearRegression().fit(rm, medv)
linear_rg.coef_
linear_rg.intercept_
#formula to calculate linear regression= medv=intercept+coef*rmv

-34.67062077643857

In [ ]:
#since we want to calcuate multiple linear regression we mix two feature
X=np.concatenate((age,rm), axis=1)
linear_mul_rg=LinearRegression().fit(X,medv)
linear_mul_rg.coef_
linear_mul_rg.intercept_

-25.277399052977106

In [ ]:
from sklearn.metrics import mean_squared_error
#calculate meansequared error
mean_squared_error(medv, linear_rg.predict(rm), squared=False)
mean_squared_error(medv, linear_mul_rg.predict(X), squared=False)

6.2971370843504495

In [ ]:
from sklearn.metrics import r2_score
#calculate rscore
#R2 for simple linear model
r2_score(medv, linear_rg.predict(rm))
r2_score(medv, linear_mul_rg.predict(X))



0.5302754804141959